title: Esteve Sanpons
subtitle: Soy un apasionado de la programación
description: >- # this means to ignore newlines until "baseurl:"
  Programador de software, diseño y creador de soluciones, tanto grandes como pequeñas.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Inicio
    url: /
  - text: Sobre mí
    url: /about
  - text: Blog
    url: /blog
  - text: Boveda
    url: /boveda
#  - text: Contacto
#    url: /contact

# Edit Author details (For multi authors check _data/authors.yml)
author_logo2: logo-me.png
author_logo: logo.png
author: Esteve Sanpons
author_bio: Mi nombre es Esteve Sanpons, y me gusta mucho la programación
author_email: "esteve@aesva.es"
author_location: Barcelona
author_website_url: "https://aesva.es"
typewrite-text: Soy un apasionado de la programación.
hero_cover_img: fondo.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
  - company_name: Mitra Global Service
    company_year: 2022 - Presente
    company_logo: mitra.png
    designation: Responsable d'equipo y programador en C/AL y AL
    description:
      Gestionar la operativa, la organización de las tareas y el análisis de los proyectos para el equipo técnico y funcional de la empresa.
      Fomentar el crecimiento del equipo, al igual que formarlo.
      Fabricación y desarrollo de producto nuevo para diferentes sectores. Realizando desde pequeñas aplicaciones que resuelven el día a día, hasta grandes desarrollos donde suplen una gran funcionalidad en las empresas.
    visibility: true
  - company_name: Grupo Empresas Engel (Ersax Trade, Engel Systems, My Tech Retail, Engel Solar, Logistica Santiga)
    company_year: 2020 - 2022
    company_logo: engel.png
    designation: Responsable del departamento y programador en C/AL
    description:
      Organizar y gestionar el departamento entero de Navision para todas las empresas del grupo. Llevando la responsabilidad de las personas a mi cargo, la toma de decisiones y gestión de los diferentes proveedores y del propio del departamento.
      Recabar los requerimientos necesarios para las empresas del grupo. Analizar y desarrollar todo lo relacionado con Navision.
      Aparte de la organización, realizar las funciones de programador del departamento.
    visibility: true
  - company_name: Netzer Consulting
    company_year: 2017 - 2020
    company_logo: netzer.jpg
    designation: Consultor y programador junior en C/AL
    description:
      Consultor y programador en Microsoft Dynamics NAV. Analizar las incidencias y los desarrollos nuevos para después poder desarrollarlos.
      Realizar todas las tareas desde la toma de requerimientos hasta él cuadre de los objetos. Lenguaje CAL desde la versión 2013 hasta la 2018.
      Trabajos a destacar. WebServices, conexiones entre bases de datos, interconexión entre extensibles y Navision, entre otros, también, intercomunicar un almacén robotizado y Navision.
      Ejecución y aplicación de Dll dentro del sistema de Navision para suplir necesidades extras de los clientes, tales como botones más grandes o conexión con básculas externas.
    visibility: true

# Education
author_education_details:
  - college_logo: bc.png
    education_year: 2022 - Presente
    college_name: Mitra Global Services
    college_degree: Programador y consultor AL
    description: Programación del lenguaje AL del ERP Business Central
    visibility: true
  - college_logo: html5-css3-js.png
    education_year: 2022 - Presente
    college_name: Mitra Global Services
    college_degree: Programador Javascript, Html y Css
    description: Programación con integraciones en Business Central con los lenguajes de programación web.
    visibility: true
  - college_logo: navision.png
    education_year: 2017 - 2020
    college_name: Empresa Netzer Consulting
    college_degree: Programador y consultor C/AL
    description: Programación del lenguaje C/AL del ERP Navision
    visibility: true
  - college_logo: java-android.png
    education_year: 2015 - 2016
    college_name: Escola Espai
    college_degree: Programador en Android y Java
    description: Nociones basicas de programación basadas en Java y Android.
    visibility: true
  - college_logo: castell-del-quer.jpg
    education_year: 1996 - 2000
    college_name: I.E.S. Castell del Quer
    college_degree: Enseñanza secundaria
    description: E.S.O.
    visibility: true
  - college_logo: pere-vila.png
    education_year: 1990 - 1996
    college_name: Escola Pere Vila
    college_degree: Enseñanza primaria
    description: Primaria
    visibility: true

# Projects
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com
    visibility: true

# social links
#twitter_username: johndoe
github_username: esanpons
#facebook_username: johndoe
linkedin_username: estevesanpons
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
telegram_username: Esanpons
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity) (es el grafico NO BORRAR)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
#jekyll-archives:
#  enabled:
#  - categories
#    layout: archive
#    permalinks:
#    category: '/category/:name/'

collections:
  articles:
    output: true
#  authors:
#    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  - scope:
      path: "assets/**"
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
#  - jekyll-gist
#  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md

destination: ./build
